# Jimeng API 常量与多语言配置
LOG_TRANSLATIONS = {
    "zh": {
        # 初始化/依赖检查相关
        "init_sdk_ver_low": "[JimengAI] 当前 SDK 版本 {current} 过低，正在自动更新至 >= {min}...",
        "init_sdk_update_ok": "[JimengAI] SDK 更新完成。",
        "init_sdk_not_found": "[JimengAI] 未检测到 {pkg},正在自动安装...",
        "init_sdk_install_ok": "[JimengAI] SDK 安装完成。",
        "init_sdk_install_fail": "[JimengAI] 自动安装失败，请手动安装: {e}",
        "init_dep_check_err": "[JimengAI] 依赖检查出错: {e}",
        
        # 控制台信息
        "api_file_not_found": "[JimengAI] 提示: 未找到 API 密钥文件。请将 'api_keys.json.example' 重命名为 'api_keys.json' 并填入您的密钥。",
        "api_file_empty": "[JimengAI] 警告: 'api_keys.json' 为空或格式不正确。",
        "api_load_error": "[JimengAI] 错误: 加载 'api_keys.json' 失败: {e}",
        "api_key_not_found": "[JimengAI] 错误: 未找到 '{key_name}' 的 API Key，请检查配置文件。",
        "est_fallback": "默认兜底",
        "est_history": "历史均值",
        "est_regression": "线性回归",
        "est_recent": "近期负载调整",
        "task_submitted_est": "[JimengAI] 任务已提交。预估生成时间: {time}s (预估方式: {method})",
        "task_info_simple": "[JimengAI] 任务 ID: {task_id} | 模型: {model}",
        "batch_submit_start": "[JimengAI] 正在提交 {count} 个任务...",
        "batch_submit_result": "[JimengAI] 提交完成。成功: {created}，失败: {failed}。",
        "batch_failed_summary": "[JimengAI] ⚠️ {count} 个任务创建失败。原因汇总:",
        "batch_failed_reason": "  - {msg}: {count} 次",
        
        # 轮询提示
        "polling_single": "[JimengAI] 任务 {task_id}: 运行中... 已耗时 {elapsed}s / 预估 {max}s",
        "polling_single_waiting": "[JimengAI] 任务排队等待资源中... (状态: {status})",
        "polling_batch_stats": "[JimengAI] 批量进度: 完成 {done}/{total}。等待中: {pending}... (耗时 {elapsed}s / 预估 {max}s) [运行中: {running}，排队: {queued}]",

        "interrupted": "\n[JimengAI] 用户中断了处理。正在尝试取消挂起任务...",
        "cancel_task_success": "[JimengAI] 已成功取消任务: {task_id}",
        "cancel_task_failed": "[JimengAI] 取消任务 {task_id} 失败: {msg}",
        "cancel_batch_summary": "[JimengAI] 批量取消完成。成功取消: {success} 个，取消失败: {failed} 个。",
        "cancel_batch_reason": "  - {msg}",
        "task_finished_single": "[JimengAI] 任务执行成功。",
        "batch_finished_stats": "[JimengAI] 批量处理完成。成功: {success}，失败: {failed}。",
        "batch_handling": "[JimengAI] 正在处理 {count} 个成功任务，按 Seed 排序并下载...",
        "batch_copying": "[JimengAI] 正在保存文件到输出目录: {path}",
        "err_download_url": "[JimengAI] 异步下载或转换失败,URL: {url}，错误: {e}",
        "err_task_create": "[JimengAI] 任务创建失败: {e}",
        "err_task_check": "[JimengAI] 检查任务状态失败 ({tid}): {e}",
        "err_task_fail_msg": "[JimengAI] 任务 {tid} 失败: {msg}",
        "err_batch_fail_all": "[JimengAI] 批量任务失败: 无任务成功。",
        "err_copy_fail": "[JimengAI] 复制文件失败: {path}，错误: {e}",
        "err_convert_tensor": "[JimengAI] 转换图片 Tensor 失败: {e}",
        "err_check_status_batch": "[JimengAI] 检查非阻塞任务状态失败: {e}",
        "download_retry": "[JimengAI] 警告: 下载失败 (尝试 {attempt}/{total})。{delay}秒后重试... 错误: {e}",
        
        # 流式生成
        "stream_recv_image": "[JimengAI] 流式接收: 第 {index} 张图片生成完毕，正在后台下载...",
        "stream_partial_fail": "[JimengAI] 流式警告: 第 {index} 张图片生成失败: {msg}",

        # 弹窗提示
        "popup_req_failed": "[JimengAI] 请求失败: {msg}",
        "popup_task_failed": "[JimengAI] 任务 {task_id} 失败: {msg}",
        "popup_batch_pending": "[JimengAI] 批量任务 ({count} 个) 处理中。请再次运行以检查结果。",
        "popup_task_pending": "[JimengAI] 任务 {task_id} 状态为 {status}。请再次运行以检查结果。",
        "popup_param_not_allowed": "[JimengAI] 参数错误: 提示词中不允许包含参数 '--{param}'。请使用节点的组件进行设置。",
        "popup_first_frame_missing": "[JimengAI] 参数错误: 使用尾帧图片时必须提供首帧图片。",
        "popup_ref_missing": "[JimengAI] 参数错误: 必须提供至少一张参考图。",
        "popup_prepare_failed": "[JimengAI] 任务准备失败: {e}",

        # 图片节点
        "err_pixels_range": "[JimengAI] 参数错误: 总像素数必须在 {min} ({min_desc}) 和 {max} ({max_desc}) 之间。当前值: {current}",
        "err_aspect_ratio": "[JimengAI] 参数错误: 宽高比必须在 {min} 和 {max} 之间。当前值: {current}",
        "err_download_img": "[JimengAI] 错误: 下载生成的图像失败。",
        "err_gen_model": "[JimengAI] 模型 {model} 生成失败: {e}",
        "err_img_limit_10": "[JimengAI] 参数错误: 输入图像数量不能超过 10 张。",
        "err_img_limit_15": "[JimengAI] 参数错误: 输入图像数 ({n}) 与最大生成数 ({max}) 之和不能超过 15。",
        "err_img_limit_group_15": "[JimengAI] 参数错误: 在组图模式下，输入参考图数量 ({n}) 加 生成图片数量 ({max}) 的总和 ({total}) 不能超过 15 张。",

        # Keys
        "combo_no_keys": "未找到密钥 (请配置 api_keys.json)",
        "popup_key_valid_err": "[JimengAI] 配置错误: 所选密钥 '{key}' 无效或未找到。请检查 api_keys.json。",

        # API 错误码映射
        "api_errors": {
            "AuthenticationError": "API 密钥无效或未找到。请检查 api_keys.json。",
            "AccessDenied": "访问被拒绝。您没有权限访问该资源或白名单未配置。",
            "AccountOverdueError": "账户欠费。请前往火山引擎控制台充值。",
            "ServiceOverdue": "服务欠费。请前往费用中心充值。",
            "ServiceNotOpen": "服务未开通。请在控制台激活对应的模型服务。",
            "ModelNotOpen": "模型未开通。请在控制台激活该模型。",
            "TaskRunningCannotCancel": "任务正在运行中，不支持取消操作。",
            "RateLimitExceeded": "请求过于频繁。请稍后重试或联系管理员增加配额。",
            "QuotaExceeded": "配额已耗尽。免费试用额度或并发限制已达到上限。",
            "ServerOverloaded": "服务器过载。请稍后重试。",
            "InternalServiceError": "内部服务错误。请稍后重试。",
            "SensitiveContentDetected": "检测到敏感内容。请修改提示词或输入图像后重试。",
            "InputTextSensitiveContentDetected": "输入文本包含敏感信息。请修改提示词。",
            "InputImageSensitiveContentDetected": "输入图像包含敏感信息。请更换图像。",
            "OutputTextSensitiveContentDetected": "生成文本包含敏感信息。",
            "OutputImageSensitiveContentDetected": "生成图像包含敏感信息。",
            "OutputVideoSensitiveContentDetected": "生成视频包含敏感信息。",
            "InvalidImageURL": "图片 URL 无效或无法解析。",
            "InvalidImageDetail": "图片 Detail 参数无效。",
            "MissingParameter": "缺少必要参数。",
            "InvalidParameter": "请求参数无效。请检查参数是否符合 API 文档要求。",
            "LastFrameNotSupported": "当前模型不支持尾帧控制。请移除尾帧图片或更换支持的模型。",
            "RefImageNotSupported": "当前模型不支持该类型的参考图输入。",
            "PromptEmpty": "提示词不能为空 (400)，请输入提示词。",
        }
    },
    "en": {
        "init_sdk_ver_low": "[JimengAI] Current SDK version {current} is too low. Auto-updating to >= {min}...",
        "init_sdk_update_ok": "[JimengAI] SDK update completed.",
        "init_sdk_not_found": "[JimengAI] Package {pkg} not found. Installing automatically...",
        "init_sdk_install_ok": "[JimengAI] SDK installation completed.",
        "init_sdk_install_fail": "[JimengAI] Auto-install failed. Please install manually: {e}",
        "init_dep_check_err": "[JimengAI] Dependency check error: {e}",
        "api_file_not_found": "[JimengAI] Info: API keys file not found. Please rename 'api_keys.json.example' to 'api_keys.json' and fill in your keys.",
        "api_file_empty": "[JimengAI] Warning: 'api_keys.json' is empty or not formatted correctly.",
        "api_load_error": "[JimengAI] Error: Failed to load 'api_keys.json': {e}",
        "api_key_not_found": "[JimengAI] Error: API Key for '{key_name}' not found.",
        "est_fallback": "Fallback Default",
        "est_history": "History Average",
        "est_regression": "Linear Regression",
        "est_recent": "Recent Load Adjustment",
        "task_submitted_est": "[JimengAI] Task submitted. Est. time: {time}s (Method: {method})",
        "task_info_simple": "[JimengAI] Task ID: {task_id} | Model: {model}",
        "batch_submit_start": "[JimengAI] Submitting batch of {count} tasks (Model: {model})...",
        "batch_submit_result": "[JimengAI] Submission complete. Created: {created}, Failed: {failed}.",
        "batch_failed_summary": "[JimengAI] ⚠️ {count} tasks failed to create. Reason summary:",
        "batch_failed_reason": "  - {msg}: {count} times",
        
        # Updated
        "polling_single": "[JimengAI] Task {task_id}: Running... {elapsed}s / {max}s elapsed",
        "polling_single_waiting": "[JimengAI] Task {task_id}: Queued and waiting for resources... (Status: {status})",
        "polling_batch_stats": "[JimengAI] Batch Progress: {done}/{total} done. {pending} pending... (Elapsed {elapsed}s / {max}s) [Run: {running}, Queue: {queued}]",

        "interrupted": "\n[JimengAI] Processing interrupted by user. Cancelling pending tasks...",
        "cancel_task_success": "[JimengAI] Successfully cancelled task: {task_id}",
        "cancel_task_failed": "[JimengAI] Failed to cancel task {task_id}: {msg}",
        "cancel_batch_summary": "[JimengAI] Batch cancellation finished. Success: {success}, Failed: {failed}.",
        "cancel_batch_reason": "  - {msg}",
        "task_finished_single": "[JimengAI] Task completed successfully.",
        "batch_finished_stats": "[JimengAI] Batch finished. Success: {success}, Failed: {failed}.",
        "batch_handling": "[JimengAI] Handling {count} successful tasks. Sorting by seed and downloading...",
        "batch_copying": "[JimengAI] Copying files to output directory: {path}",
        "err_download_url": "[JimengAI] Async download failed, URL: {url}, Error: {e}",
        "err_task_create": "[JimengAI] Task creation failed: {e}",
        "err_task_check": "[JimengAI] Failed to check status for {tid}: {e}",
        "err_task_fail_msg": "[JimengAI] Task {tid} failed: {msg}",
        "err_batch_fail_all": "[JimengAI] Batch failed: No tasks succeeded.",
        "err_copy_fail": "[JimengAI] Failed to copy file: {path}. Error: {e}",
        "err_convert_tensor": "[JimengAI] Failed to convert frame to tensor: {e}",
        "err_check_status_batch": "[JimengAI] API Error checking batch status: {e}",
        "download_retry": "[JimengAI] Warning: Download failed (Attempt {attempt}/{total}). Retrying in {delay}s... Error: {e}",
        "stream_recv_image": "[JimengAI] Streaming: Image {index} generated, downloading in background...",
        "stream_partial_fail": "[JimengAI] Streaming Warning: Image {index} failed: {msg}",
        "popup_req_failed": "[JimengAI] Request failed: {msg}",
        "popup_task_failed": "[JimengAI] Task {task_id} failed: {msg}",
        "popup_batch_pending": "[JimengAI] Batch ({count} tasks) is pending. Run again to check results.",
        "popup_task_pending": "[JimengAI] Task {task_id} is {status}. Run again to check results.",
        "popup_param_not_allowed": "[JimengAI] Parameter Error: Parameter '--{param}' is not allowed in the prompt. Please use the node's widget for this value.",
        "popup_first_frame_missing": "[JimengAI] Parameter Error: A first frame image must be provided when using a last frame image.",
        "popup_ref_missing": "[JimengAI] Parameter Error: At least one reference image must be provided.",
        "popup_prepare_failed": "[JimengAI] Failed to prepare task: {e}",
        "err_pixels_range": "[JimengAI] Parameter Error: Total pixels must be between {min} ({min_desc}) and {max} ({max_desc}). Your current: {current}",
        "err_aspect_ratio": "[JimengAI] Parameter Error: Aspect ratio must be between {min} and {max}. Your current: {current}",
        "err_download_img": "[JimengAI] Error: Failed to download the generated image.",
        "err_gen_model": "[JimengAI] Failed to generate image with model {model}: {e}",
        "err_img_limit_10": "[JimengAI] Parameter Error: The number of input images cannot exceed 10.",
        "err_img_limit_15": "[JimengAI] Parameter Error: The sum of input images ({n}) and max generated images ({max}) cannot exceed 15.",
        "err_img_limit_group_15": "[JimengAI] Parameter Error: The sum of input images ({n}) and max generated images ({max}) cannot exceed 15 in group mode (Total: {total}).",
        "combo_no_keys": "No Keys Found (Check api_keys.json)",
        "popup_key_valid_err": "[JimengAI] Config Error: Selected key '{key}' is invalid or not found. Please check api_keys.json.",
        "api_errors": {
            "AuthenticationError": "Invalid API Key (401). Please check api_keys.json.",
            "AccessDenied": "Access Denied (403). No permission or IP whitelist issue.",
            "AccountOverdueError": "Account Overdue (403). Please recharge your account.",
            "ServiceOverdue": "Service Overdue (403). Please recharge.",
            "ServiceNotOpen": "Service Not Open (403). Please activate the model service.",
            "ModelNotOpen": "Model Not Open (404). Please activate the model.",
            "TaskRunningCannotCancel": "Task is currently running and cannot be cancelled (409).",
            "RateLimitExceeded": "Rate Limit Exceeded (429). Please try again later.",
            "QuotaExceeded": "Quota Exceeded (429). Free trial or concurrency limit reached.",
            "ServerOverloaded": "Server Overloaded (429). Please try again later.",
            "InternalServiceError": "Internal Service Error (500). Please try again later.",
            "SensitiveContentDetected": "Sensitive Content Detected (400). Please change your prompt.",
            "InputTextSensitiveContentDetected": "Input text contains sensitive content (400).",
            "InputImageSensitiveContentDetected": "Input image contains sensitive content (400).",
            "OutputTextSensitiveContentDetected": "Generated text contains sensitive content (400).",
            "OutputImageSensitiveContentDetected": "Generated image contains sensitive content (400).",
            "OutputVideoSensitiveContentDetected": "Generated video contains sensitive content (400).",
            "InvalidImageURL": "Invalid Image URL (400).",
            "InvalidImageDetail": "Invalid Image Detail parameter (400).",
            "MissingParameter": "Missing Parameter (400).",
            "InvalidParameter": "Invalid Parameter (400).",
            "LastFrameNotSupported": "Last frame input is not supported by this model. Please remove it or use the Pro model.",
            "RefImageNotSupported": "Reference image input is not supported by this model.",
            "PromptEmpty": "Prompt cannot be empty (400).",
        }
    }
}

ERROR_TEXT_MATCH_RULES = {
    "output image may contain sensitive information": "OutputImageSensitiveContentDetected",
    "input text may contain sensitive information": "InputTextSensitiveContentDetected",
    "input image may contain sensitive information": "InputImageSensitiveContentDetected", 
    "output video may contain sensitive information": "OutputVideoSensitiveContentDetected",
    "generated text contains sensitive content": "OutputTextSensitiveContentDetected",
    "API key or AK/SK in the request is missing or invalid": "AuthenticationError",
    "account has an overdue balance": "AccountOverdueError",
    "exceeded the quota": "QuotaExceeded",
    "limit of the associated endpoint": "RateLimitExceeded",
    "Request failed because it is missing": "MissingParameter",
    "parameters specified in the request are not valid": "InvalidParameter",
    "not permitted to access": "AccessDenied",
    "service is unavailable": "ServiceNotOpen",
    "does not support last frame image": "LastFrameNotSupported",
    "does not support reference image": "RefImageNotSupported",
    "prompt cannot be empty": "PromptEmpty",
    "text content must contain a prompt description": "PromptEmpty",
    "because it is currently running": "TaskRunningCannotCancel",
}